service: bot-telegram-serverless

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    TELEGRAM_TOKEN: '1892088875:AAHa7e4WZcpXCf8gqW0HXuR_H30YF-GFwJU'


plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  hello:
    handler: src/handler.webhook
    events:
      - http:
          path: /webhook
          method: post
